// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: response.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CertStatus int32

const (
	CertStatus_GOOD    CertStatus = 0
	CertStatus_REVOKED CertStatus = 1
	CertStatus_UNKNOWN CertStatus = 2
)

// Enum value maps for CertStatus.
var (
	CertStatus_name = map[int32]string{
		0: "GOOD",
		1: "REVOKED",
		2: "UNKNOWN",
	}
	CertStatus_value = map[string]int32{
		"GOOD":    0,
		"REVOKED": 1,
		"UNKNOWN": 2,
	}
)

func (x CertStatus) Enum() *CertStatus {
	p := new(CertStatus)
	*p = x
	return p
}

func (x CertStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CertStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_response_proto_enumTypes[0].Descriptor()
}

func (CertStatus) Type() protoreflect.EnumType {
	return &file_response_proto_enumTypes[0]
}

func (x CertStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CertStatus.Descriptor instead.
func (CertStatus) EnumDescriptor() ([]byte, []int) {
	return file_response_proto_rawDescGZIP(), []int{0}
}

type MerkleProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Siblings      [][]byte               `protobuf:"bytes,1,rep,name=siblings,proto3" json:"siblings,omitempty"`
	Path          uint32                 `protobuf:"varint,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleProof) Reset() {
	*x = MerkleProof{}
	mi := &file_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleProof) ProtoMessage() {}

func (x *MerkleProof) ProtoReflect() protoreflect.Message {
	mi := &file_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleProof.ProtoReflect.Descriptor instead.
func (*MerkleProof) Descriptor() ([]byte, []int) {
	return file_response_proto_rawDescGZIP(), []int{0}
}

func (x *MerkleProof) GetSiblings() [][]byte {
	if x != nil {
		return x.Siblings
	}
	return nil
}

func (x *MerkleProof) GetPath() uint32 {
	if x != nil {
		return x.Path
	}
	return 0
}

type ExclusionProofSorted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LVal          []byte                 `protobuf:"bytes,1,opt,name=l_val,json=lVal,proto3" json:"l_val,omitempty"`
	RVal          []byte       `protobuf:"bytes,2,opt,name=r_val,json=rVal,proto3" json:"r_val,omitempty"`
	LProof        *MerkleProof `protobuf:"bytes,3,opt,name=l_proof,json=lProof,proto3" json:"l_proof,omitempty"`
	RProof        *MerkleProof `protobuf:"bytes,4,opt,name=r_proof,json=rProof,proto3" json:"r_proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExclusionProofSorted) Reset() {
	*x = ExclusionProofSorted{}
	mi := &file_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExclusionProofSorted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExclusionProofSorted) ProtoMessage() {}

func (x *ExclusionProofSorted) ProtoReflect() protoreflect.Message {
	mi := &file_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExclusionProofSorted.ProtoReflect.Descriptor instead.
func (*ExclusionProofSorted) Descriptor() ([]byte, []int) {
	return file_response_proto_rawDescGZIP(), []int{1}
}

func (x *ExclusionProofSorted) GetLVal() []byte {
	if x != nil {
		return x.LVal
	}
	return nil
}

func (x *ExclusionProofSorted) GetRVal() []byte {
	if x != nil {
		return x.RVal
	}
	return nil
}

func (x *ExclusionProofSorted) GetLProof() *MerkleProof {
	if x != nil {
		return x.LProof
	}
	return nil
}

func (x *ExclusionProofSorted) GetRProof() *MerkleProof {
	if x != nil {
		return x.RProof
	}
	return nil
}

type SparseCompactMerkleProof struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SideNodes             [][]byte               `protobuf:"bytes,1,rep,name=side_nodes,json=sideNodes,proto3" json:"side_nodes,omitempty"`
	NonMembershipLeafData []byte                 `protobuf:"bytes,2,opt,name=non_membership_leaf_data,json=nonMembershipLeafData,proto3" json:"non_membership_leaf_data,omitempty"`
	BitMask               []byte                 `protobuf:"bytes,3,opt,name=bit_mask,json=bitMask,proto3" json:"bit_mask,omitempty"`
	NumSideNodes          int32                  `protobuf:"varint,4,opt,name=num_side_nodes,json=numSideNodes,proto3" json:"num_side_nodes,omitempty"`
	SiblingData           []byte                 `protobuf:"bytes,5,opt,name=sibling_data,json=siblingData,proto3" json:"sibling_data,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SparseCompactMerkleProof) Reset() {
	*x = SparseCompactMerkleProof{}
	mi := &file_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SparseCompactMerkleProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SparseCompactMerkleProof) ProtoMessage() {}

func (x *SparseCompactMerkleProof) ProtoReflect() protoreflect.Message {
	mi := &file_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SparseCompactMerkleProof.ProtoReflect.Descriptor instead.
func (*SparseCompactMerkleProof) Descriptor() ([]byte, []int) {
	return file_response_proto_rawDescGZIP(), []int{2}
}

func (x *SparseCompactMerkleProof) GetSideNodes() [][]byte {
	if x != nil {
		return x.SideNodes
	}
	return nil
}

func (x *SparseCompactMerkleProof) GetNonMembershipLeafData() []byte {
	if x != nil {
		return x.NonMembershipLeafData
	}
	return nil
}

func (x *SparseCompactMerkleProof) GetBitMask() []byte {
	if x != nil {
		return x.BitMask
	}
	return nil
}

func (x *SparseCompactMerkleProof) GetNumSideNodes() int32 {
	if x != nil {
		return x.NumSideNodes
	}
	return 0
}

func (x *SparseCompactMerkleProof) GetSiblingData() []byte {
	if x != nil {
		return x.SiblingData
	}
	return nil
}

type CombinedProof struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	IssueRoot     []byte                    `protobuf:"bytes,1,opt,name=issue_root,json=issueRoot,proto3" json:"issue_root,omitempty"`
	IssueEpochRev []byte                    `protobuf:"bytes,2,opt,name=issue_epoch_rev,json=issueEpochRev,proto3" json:"issue_epoch_rev,omitempty"`
	RevRoot       []byte                    `protobuf:"bytes,3,opt,name=rev_root,json=revRoot,proto3" json:"rev_root,omitempty"`
	RevEpochIssue []byte                    `protobuf:"bytes,4,opt,name=rev_epoch_issue,json=revEpochIssue,proto3" json:"rev_epoch_issue,omitempty"`
	IssueDate     *timestamppb.Timestamp    `protobuf:"bytes,5,opt,name=issue_date,json=issueDate,proto3" json:"issue_date,omitempty"`
	IssueProof    *MerkleProof              `protobuf:"bytes,6,opt,name=issue_proof,json=issueProof,proto3" json:"issue_proof,omitempty"`
	NonIssueProof *ExclusionProofSorted     `protobuf:"bytes,7,opt,name=non_issue_proof,json=nonIssueProof,proto3" json:"non_issue_proof,omitempty"`
	RevProof      *SparseCompactMerkleProof `protobuf:"bytes,8,opt,name=rev_proof,json=revProof,proto3" json:"rev_proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombinedProof) Reset() {
	*x = CombinedProof{}
	mi := &file_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombinedProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombinedProof) ProtoMessage() {}

func (x *CombinedProof) ProtoReflect() protoreflect.Message {
	mi := &file_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombinedProof.ProtoReflect.Descriptor instead.
func (*CombinedProof) Descriptor() ([]byte, []int) {
	return file_response_proto_rawDescGZIP(), []int{3}
}

func (x *CombinedProof) GetIssueRoot() []byte {
	if x != nil {
		return x.IssueRoot
	}
	return nil
}

func (x *CombinedProof) GetIssueEpochRev() []byte {
	if x != nil {
		return x.IssueEpochRev
	}
	return nil
}

func (x *CombinedProof) GetRevRoot() []byte {
	if x != nil {
		return x.RevRoot
	}
	return nil
}

func (x *CombinedProof) GetRevEpochIssue() []byte {
	if x != nil {
		return x.RevEpochIssue
	}
	return nil
}

func (x *CombinedProof) GetIssueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.IssueDate
	}
	return nil
}

func (x *CombinedProof) GetIssueProof() *MerkleProof {
	if x != nil {
		return x.IssueProof
	}
	return nil
}

func (x *CombinedProof) GetNonIssueProof() *ExclusionProofSorted {
	if x != nil {
		return x.NonIssueProof
	}
	return nil
}

func (x *CombinedProof) GetRevProof() *SparseCompactMerkleProof {
	if x != nil {
		return x.RevProof
	}
	return nil
}

type LandmarkProof struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LogProof       [][]byte               `protobuf:"bytes,1,rep,name=log_proof,json=logProof,proto3" json:"log_proof,omitempty"`
	LogIndex       uint64                 `protobuf:"varint,2,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`
	NewestLogProof [][]byte               `protobuf:"bytes,3,rep,name=newest_log_proof,json=newestLogProof,proto3" json:"newest_log_proof,omitempty"`
	NewestLogIndex uint64         `protobuf:"varint,4,opt,name=newest_log_index,json=newestLogIndex,proto3" json:"newest_log_index,omitempty"`
	CombinedProof  *CombinedProof `protobuf:"bytes,5,opt,name=combined_proof,json=combinedProof,proto3" json:"combined_proof,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LandmarkProof) Reset() {
	*x = LandmarkProof{}
	mi := &file_response_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LandmarkProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandmarkProof) ProtoMessage() {}

func (x *LandmarkProof) ProtoReflect() protoreflect.Message {
	mi := &file_response_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandmarkProof.ProtoReflect.Descriptor instead.
func (*LandmarkProof) Descriptor() ([]byte, []int) {
	return file_response_proto_rawDescGZIP(), []int{4}
}

func (x *LandmarkProof) GetLogProof() [][]byte {
	if x != nil {
		return x.LogProof
	}
	return nil
}

func (x *LandmarkProof) GetLogIndex() uint64 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

func (x *LandmarkProof) GetNewestLogProof() [][]byte {
	if x != nil {
		return x.NewestLogProof
	}
	return nil
}

func (x *LandmarkProof) GetNewestLogIndex() uint64 {
	if x != nil {
		return x.NewestLogIndex
	}
	return 0
}

func (x *LandmarkProof) GetCombinedProof() *CombinedProof {
	if x != nil {
		return x.CombinedProof
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        CertStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=ocsp.CertStatus" json:"status,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Proof         *LandmarkProof         `protobuf:"bytes,3,opt,name=proof,proto3" json:"proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_response_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_response_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_response_proto_rawDescGZIP(), []int{5}
}

func (x *Response) GetStatus() CertStatus {
	if x != nil {
		return x.Status
	}
	return CertStatus_GOOD
}

func (x *Response) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Response) GetProof() *LandmarkProof {
	if x != nil {
		return x.Proof
	}
	return nil
}

var File_response_proto protoreflect.FileDescriptor

const file_response_proto_rawDesc = "" +
	"\n" +
	"\x0eresponse.proto\x12\x04ocsp\x1a\x1fgoogle/protobuf/timestamp.proto\"=\n" +
	"\vMerkleProof\x12\x1a\n" +
	"\bsiblings\x18\x01 \x03(\fR\bsiblings\x12\x12\n" +
	"\x04path\x18\x02 \x01(\rR\x04path\"\x98\x01\n" +
	"\x14ExclusionProofSorted\x12\x13\n" +
	"\x05l_val\x18\x01 \x01(\fR\x04lVal\x12\x13\n" +
	"\x05r_val\x18\x02 \x01(\fR\x04rVal\x12*\n" +
	"\al_proof\x18\x03 \x01(\v2\x11.ocsp.MerkleProofR\x06lProof\x12*\n" +
	"\ar_proof\x18\x04 \x01(\v2\x11.ocsp.MerkleProofR\x06rProof\"\xd6\x01\n" +
	"\x18SparseCompactMerkleProof\x12\x1d\n" +
	"\n" +
	"side_nodes\x18\x01 \x03(\fR\tsideNodes\x127\n" +
	"\x18non_membership_leaf_data\x18\x02 \x01(\fR\x15nonMembershipLeafData\x12\x19\n" +
	"\bbit_mask\x18\x03 \x01(\fR\abitMask\x12$\n" +
	"\x0enum_side_nodes\x18\x04 \x01(\x05R\fnumSideNodes\x12!\n" +
	"\fsibling_data\x18\x05 \x01(\fR\vsiblingData\"\x89\x03\n" +
	"\rCombinedProof\x12\x1d\n" +
	"\n" +
	"issue_root\x18\x01 \x01(\fR\tissueRoot\x12&\n" +
	"\x0fissue_epoch_rev\x18\x02 \x01(\fR\rissueEpochRev\x12\x19\n" +
	"\brev_root\x18\x03 \x01(\fR\arevRoot\x12&\n" +
	"\x0frev_epoch_issue\x18\x04 \x01(\fR\rrevEpochIssue\x129\n" +
	"\n" +
	"issue_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tissueDate\x122\n" +
	"\vissue_proof\x18\x06 \x01(\v2\x11.ocsp.MerkleProofR\n" +
	"issueProof\x12B\n" +
	"\x0fnon_issue_proof\x18\a \x01(\v2\x1a.ocsp.ExclusionProofSortedR\rnonIssueProof\x12;\n" +
	"\trev_proof\x18\b \x01(\v2\x1e.ocsp.SparseCompactMerkleProofR\brevProof\"\xd9\x01\n" +
	"\rLandmarkProof\x12\x1b\n" +
	"\tlog_proof\x18\x01 \x03(\fR\blogProof\x12\x1b\n" +
	"\tlog_index\x18\x02 \x01(\x04R\blogIndex\x12(\n" +
	"\x10newest_log_proof\x18\x03 \x03(\fR\x0enewestLogProof\x12(\n" +
	"\x10newest_log_index\x18\x04 \x01(\x04R\x0enewestLogIndex\x12:\n" +
	"\x0ecombined_proof\x18\x05 \x01(\v2\x13.ocsp.CombinedProofR\rcombinedProof\"\x99\x01\n" +
	"\bResponse\x12(\n" +
	"\x06status\x18\x01 \x01(\x0e2\x10.ocsp.CertStatusR\x06status\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12)\n" +
	"\x05proof\x18\x03 \x01(\v2\x13.ocsp.LandmarkProofR\x05proof*0\n" +
	"\n" +
	"CertStatus\x12\b\n" +
	"\x04GOOD\x10\x00\x12\v\n" +
	"\aREVOKED\x10\x01\x12\v\n" +
	"\aUNKNOWN\x10\x02B\x1eZ\x1cmerkle-ocsp/internal/ocsp/pbb\x06proto3"

var (
	file_response_proto_rawDescOnce sync.Once
	file_response_proto_rawDescData []byte
)

func file_response_proto_rawDescGZIP() []byte {
	file_response_proto_rawDescOnce.Do(func() {
		file_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_response_proto_rawDesc), len(file_response_proto_rawDesc)))
	})
	return file_response_proto_rawDescData
}

var file_response_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_response_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_response_proto_goTypes = []any{
	(CertStatus)(0),                  // 0: ocsp.CertStatus
	(*MerkleProof)(nil),              // 1: ocsp.MerkleProof
	(*ExclusionProofSorted)(nil),     // 2: ocsp.ExclusionProofSorted
	(*SparseCompactMerkleProof)(nil), // 3: ocsp.SparseCompactMerkleProof
	(*CombinedProof)(nil),            // 4: ocsp.CombinedProof
	(*LandmarkProof)(nil),            // 5: ocsp.LandmarkProof
	(*Response)(nil),                 // 6: ocsp.Response
	(*timestamppb.Timestamp)(nil),    // 7: google.protobuf.Timestamp
}
var file_response_proto_depIdxs = []int32{
	1,  // 0: ocsp.ExclusionProofSorted.l_proof:type_name -> ocsp.MerkleProof
	1,  // 1: ocsp.ExclusionProofSorted.r_proof:type_name -> ocsp.MerkleProof
	7,  // 2: ocsp.CombinedProof.issue_date:type_name -> google.protobuf.Timestamp
	1,  // 3: ocsp.CombinedProof.issue_proof:type_name -> ocsp.MerkleProof
	2,  // 4: ocsp.CombinedProof.non_issue_proof:type_name -> ocsp.ExclusionProofSorted
	3,  // 5: ocsp.CombinedProof.rev_proof:type_name -> ocsp.SparseCompactMerkleProof
	4,  // 6: ocsp.LandmarkProof.combined_proof:type_name -> ocsp.CombinedProof
	0,  // 7: ocsp.Response.status:type_name -> ocsp.CertStatus
	7,  // 8: ocsp.Response.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 9: ocsp.Response.proof:type_name -> ocsp.LandmarkProof
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_response_proto_init() }
func file_response_proto_init() {
	if File_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_response_proto_rawDesc), len(file_response_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_response_proto_goTypes,
		DependencyIndexes: file_response_proto_depIdxs,
		EnumInfos:         file_response_proto_enumTypes,
		MessageInfos:      file_response_proto_msgTypes,
	}.Build()
	File_response_proto = out.File
	file_response_proto_goTypes = nil
	file_response_proto_depIdxs = nil
}
